FROM ghcr.io/utrechtuniversity/ricgraph:latest

# Install dependencies
COPY ricgraph/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm /tmp/requirements.txt

# Copy entrypoint
COPY --chmod=755 ricgraph/ricgraph_entrypoint.sh /usr/local/bin/ricgraph_entrypoint.sh

# Copy application code
COPY ricgraph/ricgraph_queries.py /app/ricgraph/ricgraph_queries.py

ENTRYPOINT ["/usr/local/bin/ricgraph_entrypoint.sh"]
