FROM ghcr.io/utrechtuniversity/ricgraph:latest

# Install dependencies
COPY ricgraph/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm /tmp/requirements.txt

# Copy application code
COPY ricgraph/ /work/
RUN chmod +x /work/ricgraph_entrypoint.sh

ENTRYPOINT ["/work/ricgraph_entrypoint.sh"]