apiVersion: v1
kind: Pod
metadata:
  name: research-ai-prod
spec:
  containers:
    - name: api
      image: research-ai-api:prod
      envFrom:
        - configMapRef:
            name: research-ai-env

    - name: frontend
      image: research-ai-frontend:prod
      ports:
        - containerPort: 80
        - containerPort: 443
      volumeMounts:
        - name: caddy-data
          mountPath: /data
        - name: caddy-config
          mountPath: /config

    - name: ricgraph
      image: ghcr.io/utrechtuniversity/ricgraph:latest
      ports:
        - containerPort: 3030 # Web Explorer
      volumeMounts:
        # runs its own neo4j database
        - name: ricgraph-data
          mountPath: /var/lib/neo4j/data

  volumes:
    - name: caddy-data
      persistentVolumeClaim:
        claimName: caddy-data-pvc
    - name: caddy-config
      persistentVolumeClaim:
        claimName: caddy-config-pvc
    - name: ricgraph-data
      persistentVolumeClaim:
        claimName: ricgraph-data-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ricgraph-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
