import React, { useState, useRef, useEffect } from 'react';
import './MiddlePanel.css';

// Mock function that returns predefined text simulating an LLM streaming response
//When the live API is connected, you'll simply replace the \`mockGenerateResponse\` function with actual API calls using fetch or Server-Sent Events (SSE).
const mockGenerateResponse = (
  onChunk: (chunk: string) => void,
  onComplete: () => void
) => {
  const predefinedText = 
  
`This is a simulated response from Research AI. 

In the future, this middle panel will be connected to a live LLM API. 
For now, it demonstrates the ability to stream text as it is being generated by the AI.

Here are a few features of this setup:
1. It supports rendering text incrementally.
2. The UI can display a typing indicator while generating.
3. The scrolling can follow the text as it grows.

End of simulated response.`;
  
  const words = predefinedText.split(/(\s+)/); // Split by whitespace but keep the whitespace
  let currentIndex = 0;

  const intervalId = setInterval(() => {
    if (currentIndex < words.length) {
      onChunk(words[currentIndex]);
      currentIndex++;
    } else {
      clearInterval(intervalId);
      onComplete();
    }
  }, 20); // Adjust speed here (20ms per word/space)

  return () => clearInterval(intervalId); // Return cleanup function
};

export const MiddlePanel: React.FC = () => {
  const [text, setText] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const outputBoxRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom when text changes and we are generating
  useEffect(() => {
    if (outputBoxRef.current && isGenerating) {
      outputBoxRef.current.scrollTop = outputBoxRef.current.scrollHeight;
    }
  }, [text, isGenerating]);

  const handleGenerate = () => {
    if (isGenerating) return;
    
    setText('');
    setIsGenerating(true);
    
    // Simulate API call
    mockGenerateResponse(
      (chunk) => {
        setText((prev) => prev + chunk);
      },
      () => {
        setIsGenerating(false);
      }
    );
  };

  return (
    <div className="middle-panel-container">
      <div className="middle-panel-header">
        <h2>AI Output</h2>
      </div>
      
      <div 
        ref={outputBoxRef}
        className={`llm-output-box ${isGenerating ? 'generating' : ''}`}
      >
        {text || (
          <span style={{ color: '#888', fontStyle: 'italic' }}>
            Click generate to see a simulated AI response
          </span>
        )}
      </div>
      
      <div className="action-buttons">
        <button 
          className="generate-btn" 
          onClick={handleGenerate} 
          disabled={isGenerating}
        >
          {isGenerating ? 'Generating...' : 'Generate Response (temporary button)'}
        </button>
      </div>
    </div>
  );
};
