import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import './App.css';
import { LeftPanel } from './components/LeftPanel';
import { MiddlePanel } from './components/MiddlePanel';
import { RightPanel } from './components/RightPanel';
import type { EntitySuggestion } from './types';
import api from './api';

/*
   Mock function that returns predefined text simulating an LLM streaming response.
   In production replace this with real API calls (fetch or SSE). The function
   receives two callbacks:
     - onChunk: called for each piece of text as it streams.
     - onComplete: called when streaming finishes.
 */
// const mockGenerateResponse = (
//   onChunk: (chunk: string) => void,
//   onComplete: () => void
// ) => {
//   const predefinedText =

// `This is a simulated response from the LLM.

// In the future, this middle panel will be connected to a live LLM API.
// For now, it demonstrates the ability to stream text as it is being generated by the AI.

// Here are a few features of this setup:
// 1. It supports rendering text incrementally.
// 2. The UI can display a typing indicator while generating.
// 3. The scrolling can follow the text as it grows.

// End of simulated response.`;

//   const words = predefinedText.split(/(\s+)/); // Split by whitespace but keep the whitespace
//   let currentIndex = 0;

//   const intervalId = setInterval(() => {
//     if (currentIndex < words.length) {
//       onChunk(words[currentIndex]);
//       currentIndex++;
//     } else {
//       clearInterval(intervalId);
//       onComplete();
//     }
//   }, 20); // Adjust speed here (20ms per word/space)

//   return () => clearInterval(intervalId); // Return cleanup function
// };

const generateResponse = async (
  prompt: string, 
  onChunk: (chunk: string) => void, 
  onComplete: () => void
) => {
  try {
    const response = await api.post('/chat', {
      model: 'llama3',
      messages: [{ role: 'user', content: prompt }],
      stream: false,
    });
  
    const text = response.data?.message?.content ?? '';
    onChunk(text);
    onComplete();
  } catch (error) {
    onChunk('Error: ' + (error instanceof Error ? error.message : 'Unknown error'));
    onComplete();
  }
};


// Main App component – orchestrates state and renders the three‑panel layout.
const App = () => {
  const [selectedEntity, setSelectedEntity] = useState<EntitySuggestion | null>(null);
  const [responseText, setResponseText] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);

  const handleGenerate = (prompt: string) => {
    if (isGenerating) return;

    setResponseText('');
    setIsGenerating(true);

    // mockGenerateResponse(
    //   (chunk) => {
    //     setResponseText((prev) => prev + chunk);
    //   },
    //   () => {
    //     setIsGenerating(false);
    //   }
    // );

    generateResponse(
      prompt,
      (chunk) => setResponseText((prev) => prev + chunk),
      () => setIsGenerating(false)
    );
  };

  const { t, i18n } = useTranslation();
  const language = i18n.language as 'en' | 'nl';

  const changeLanguage = (lng: 'en' | 'nl') => {
    i18n.changeLanguage(lng);
  };

  return (
    <div className="app-container">
      <header className="app-header">
        <h1>{t('header.title')}</h1>
        <div className="language-buttons">
          <button
            className={`lang-btn ${language === 'nl' ? 'active' : ''}`}
            onClick={() => changeLanguage('nl')}
          >
            NL
          </button>
          <button
            className={`lang-btn ${language === 'en' ? 'active' : ''}`}
            onClick={() => changeLanguage('en')}
          >
            EN
          </button>
        </div>
      </header>
      <main className="app-main">
        <LeftPanel
          selectedEntity={selectedEntity}
          onAsk={handleGenerate}
          isGenerating={isGenerating}
          onEntitySelect={setSelectedEntity}
          onEntityClear={() => setSelectedEntity(null)}
        />
        <div className="middle-panel">
          <MiddlePanel text={responseText} isGenerating={isGenerating} />
        </div>
        <RightPanel selectedEntity={selectedEntity} />
      </main>
    </div>
  );
};

export default App;
