import { useState } from 'react';
import './App.css';
import { LeftPanel } from './components/LeftPanel';
import { MiddlePanel } from './components/MiddlePanel';

// Mock function that returns predefined text simulating an LLM streaming response
// When the live API is connected, you'll simply replace the `mockGenerateResponse` function with actual API calls using fetch or Server-Sent Events (SSE).
const mockGenerateResponse = (
  onChunk: (chunk: string) => void,
  onComplete: () => void
) => {
  const predefinedText = 
  
`This is a simulated response from Research AI. 

In the future, this middle panel will be connected to a live LLM API. 
For now, it demonstrates the ability to stream text as it is being generated by the AI.

Here are a few features of this setup:
1. It supports rendering text incrementally.
2. The UI can display a typing indicator while generating.
3. The scrolling can follow the text as it grows.

End of simulated response.`;
  
  const words = predefinedText.split(/(\s+)/); // Split by whitespace but keep the whitespace
  let currentIndex = 0;

  const intervalId = setInterval(() => {
    if (currentIndex < words.length) {
      onChunk(words[currentIndex]);
      currentIndex++;
    } else {
      clearInterval(intervalId);
      onComplete();
    }
  }, 20); // Adjust speed here (20ms per word/space)

  return () => clearInterval(intervalId); // Return cleanup function
};

const App = () => {
  const [language, setLanguage] = useState<'nl' | 'en'>('nl');
  const [responseText, setResponseText] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);

  const handleGenerate = () => {
    if (isGenerating) return;
    
    setResponseText('');
    setIsGenerating(true);
    
    mockGenerateResponse(
      (chunk) => {
        setResponseText((prev) => prev + chunk);
      },
      () => {
        setIsGenerating(false);
      }
    );
  };

  return (
    <div className="app-container">
      <header className="app-header">
        <h1>Research AI Assistant</h1>
        <div className="language-buttons">
          <button 
            className={`lang-btn ${language === 'nl' ? 'active' : ''}`}
            onClick={() => setLanguage('nl')}
          >
            NL
          </button>
          <button 
            className={`lang-btn ${language === 'en' ? 'active' : ''}`}
            onClick={() => setLanguage('en')}
          >
            EN
          </button>
        </div>
      </header>
      <main className="app-main">
        <LeftPanel onAsk={handleGenerate} isGenerating={isGenerating} />
        <div className="middle-panel">
          <MiddlePanel text={responseText} isGenerating={isGenerating} />
        </div>
        <div className="right-panel">
          {/* Todo: Connections panel */}
          <div className="placeholder-panel">
            <p>Right column - Connections panel</p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default App;
