FROM docker.io/library/python:3.12-bookworm

WORKDIR /work

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ /work/

CMD ["bash","-lc","uvicorn app.main:app --host 0.0.0.0 --port 8000"]
